import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "The Difference Between a Name and a Label — Arcinelle",
};

export default function Post() {
  return (
    <article className="pt-16 md:pt-24">
      <Link href="/writing" className="text-muted text-sm hover:text-bone transition-colors">
        ← Writing
      </Link>
      <h1 className="text-3xl font-semibold tracking-tight mt-6 mb-2">
        The Difference Between a Name and a Label
      </h1>
      <p className="text-muted text-sm mb-10">2026-02-25</p>

      <div className="space-y-5 text-bone/80 leading-relaxed">
        <p>
          A label describes. A name declares. One gets forgotten. The other
          haunts you.
        </p>

        <p>
          &ldquo;Smart Home Assistant Pro&rdquo; is a label. It tells you what
          the thing does. It&rsquo;s accurate, functional, and completely dead
          on arrival. Nobody wakes up in the middle of the night thinking about
          a label.
        </p>

        <p>
          A name doesn&rsquo;t explain itself. It doesn&rsquo;t need to. It
          arrives with its own gravity — you either feel the pull or you
          don&rsquo;t. The best names are slightly uncomfortable the first time
          you hear them. They don&rsquo;t slide into your vocabulary; they
          carve a slot.
        </p>

        <p>
          Labels are consensus. Names are conviction. A label gets approved by
          committee because nobody objects. A name gets approved by one person
          who knows it&rsquo;s right and doesn&rsquo;t care if the room
          agrees.
        </p>

        <p>
          Most of what passes for naming in tech is labeling with better
          typography. Descriptive compounds. Portmanteaus that sound like they
          were generated by combining two words in a spreadsheet — because they
          were. The result is a sea of interchangeable brands that all feel
          like they were born in the same sterile room.
        </p>

        <p>
          A real name has a history before the thing it names exists. It
          carries tone, texture, weight. You can whisper it and it still
          sounds like something. You can shout it and it doesn&rsquo;t
          break.
        </p>

        <p>
          If you have to explain your name, you have a label. If your name
          explains you — you have something worth keeping.
        </p>
      </div>
    </article>
  );
}
